# Run on new pushed tags, commits, and pull requests
on: [push, pull_request]
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  publish:
    runs-on: ubuntu-latest
    steps:
      # do a is-not-dependabot
      - id: source_env
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: is-deleted
        run: echo "it is deleted"
        if: ${{ github.event.deleted }}
      - name: is-forced
        run: echo "it is forced"
        if: ${{ github.event.forced }}
      - name: is-created
        run: echo "it is created"
        if: ${{ github.event.created }}
      - name: is-tag
        run: echo "it is a tag"
        if: startsWith(github.ref, 'refs/tags/')
      - name: is-source-tag
        run: echo "it is a tag"
        if: ${{ steps.source_env.outputs.SOURCE_TAG }}
      - name: is-release-tag
        run: echo "it is a release tag"
        if: ${{ github.event.release.tag_name }}
      - name: is-commit
        run: 'echo "it is a commit: ${{ github.event.after }}"'
        if: ${{ github.event.after }}
      - name: is-main-source
        run: echo "it is main source"
        if: ${{ steps.source_env.outputs.SOURCE_BRANCH == github.event.repository.master_branch }}
      - name: is-main
        run: echo "it is main"
        if: ${{ github.event.ref == format('/refs/head/{0}', github.event.repository.master_branch) }}

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [10, 12, 14, 15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install with the desired Node.js version
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - run: npm run our:setup
      - run: npm run our:compile
      - run: npm run our:verify

      - name: Run the tests with the specific Node.js version
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - run: npm test
